# Generated by Django 4.1.7 on 2023-04-24 03:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pastel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(validators=[django.core.validators.MaxValueValidator(96), django.core.validators.MinValueValidator(0)])),
                ('end', models.IntegerField(validators=[django.core.validators.MaxValueValidator(96), django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=datetime.date.today)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.color')),
            ],
        ),
    ]
