# Generated by Django 4.1.7 on 2023-04-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_collabmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sentMail',
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentMail', models.BooleanField(default=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event')),
            ],
        ),
    ]
