# Generated by Django 4.1.7 on 2023-04-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='(No title)', max_length=50),
        ),
    ]
