# Generated by Django 3.2.19 on 2023-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
